services:
  client:
    build:
      context: ./client
      dockerfile: ../Dockerfile.client
    ports:
      - "3000:3000"
    depends_on:
      - server
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - PORT=3000
      - CHOKIDAR_USEPOLLING=true
  server:
    build: ./server
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/siteproject
      - PORT=5000
    volumes:
      - ./server:/app
      - /app/node_modules
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
