services:
  client:
    build: ./src/client
    ports:
      - "3000:3000"
    depends_on:
      - server
    volumes:
      - ./src/client:/app
      - /app/node_modules
    environment:
      - VITE_PORT=3000
      - CHOKIDAR_USEPOLLING=true
  server:
    build: ./src/server
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/siteproject
      - PORT=5000
    volumes:
      - ./src/server:/app
      - /app/node_modules
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
